Algoritmo "questao1"
// Fazer um algoritmo que peça um número, e ao final,
//informe se o número digitado está acima de 1000 ou
//abaixo de 1000.
Var
// Seção de Declarações das variáveis 
num: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite um número inteiro")
leia(num)

se (num < 1000) entao
   escreval(num, " é menor que 1000")

senao
     escreval(num, " é maior ou igual a 1000")
fimse


Fimalgoritmo